# Generated by Django 2.2.3 on 2019-07-06 06:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='likes_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 6, 48, 8, 217375, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.CharField(max_length=50),
        ),
    ]
