# Generated by Django 2.2.3 on 2019-07-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190706_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes_total',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(),
        ),
    ]
