# Generated by Django 2.2.3 on 2019-07-06 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190706_0637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
